#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-AsForm
version:      1.1
version_from: AsForm.pm
installdirs:  site
requires:
    Class::DBI:                    0.94

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
