# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-AsForm
version:      2.4
version_from: AsForm.pm
installdirs:  site
requires:
    Class::DBI:                    0.94
    Class::DBI::Plugin::Type:      0
    DBI:                           1.21
    HTML::Element:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
